"""The `repomedic agents` command — a self-describing integration guide.

Coding agents run `repomedic agents` once to learn the whole tool surface
without reading any docs or source. The canonical text lives in the
packaged ``data/AGENTS.md``; ``docs/AGENTS.md`` in the repository is a
generated byte-equal copy (guarded by ``tests/test_docs_sync.py``), so the
guide can never drift between the CLI and the docs.
"""

from __future__ import annotations

# The py37 compatibility rule does not apply — this package requires 3.11+.
from importlib.resources import files  # repomedic: ignore[python.lang.compatibility.*]


def get_agent_guide() -> str:
    """Return the agent integration guide as markdown."""
    return (files("repomedic") / "data" / "AGENTS.md").read_text(encoding="utf-8")
